discovery:
  image: zhouwei/eureka-service
  ports:
   - "8761:8761"
monitoradmin:
  image: zhouwei/monitor-admin-server
  ports:
   - "9090:9090"
  links:
   - discovery 
configserver:
  image: zhouwei/config-service
  ports:
   - "8888:8888"
  links:
   - discovery
   - monitoradmin
hystrix:
  image: zhouwei/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
gateway:
  image: zhouwei/api-gateway-service
  ports:
   - "10000:10000"
  links:
   - discovery
   - monitoradmin
   - configserver
   - simpleserver
   - simpleserverui
#   - simpleui
simpleserver:
  image: zhouwei/simple-service
  ports:
   - "8088:8088"
  links:
   - discovery
   - monitoradmin
   - configserver
simpleserverui:
  image: zhouwei/simple-service-ui
  ports:
   - "8090:8090"
  links:
   - discovery
   - monitoradmin
   - configserver
#simpleui:
#  image: zhouwei/simple-ui
#  ports:
#   - "8089:8089"
#  links:
#   - discovery
#   - monitoradmin
#   - configserver   
#movie:
#  image: kbastani/movie-microservice
#  links:
#   - discovery
#   - configserver
#recommendation:
#  image: kbastani/recommendation-microservice
#  links:
#   - discovery
#   - configserver
#moviesui:
#  image: kbastani/movies-ui
#  ports:
#     - "9006:9006"
#  links:
#   - discovery
#   - configserver